on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: projectdeploycr.azurecr.io
        username: ${{ secrets.acr_projectdeploycr_username }}
        password: ${{ secrets.acr_projectdeploycr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Chat_App" -f  "Chat_App/Dockerfile" -t projectdeploycr.azurecr.io/projectdeploycluster:${{ github.sha }} --label dockerfile-path=Chat_App/Dockerfile
        docker push projectdeploycr.azurecr.io/projectdeploycluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_projectdeploycluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep projectdeployclustera414 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace projectdeployclustera414`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: projectdeployclustera414
        container-registry-url: projectdeploycr.azurecr.io
        container-registry-username: ${{ secrets.acr_projectdeploycr_username }}
        container-registry-password: ${{ secrets.acr_projectdeploycr_password }}
        secret-name: projectdeplodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: projectdeployclustera414
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          projectdeploycr.azurecr.io/projectdeploycluster:${{ github.sha }}
        imagepullsecrets: |
          projectdeplodockerauth
